// Constantes globales del sistema

export const APP_CONFIG = {
  NOMBRE: 'Sistema de Gestión de Horarios - UNT',
  VERSION: '1.0.0',
  UNIVERSIDAD: 'Universidad Nacional de Trujillo',
  ESCUELA: 'Escuela de Ingeniería de Sistemas',
};

export const HORARIOS = {
  HORA_INICIO_DEFAULT: '08:00',
  HORA_FIN_DEFAULT: '20:00',
  /** Última hora de fin de clase (9:00 p.m.) */
  HORA_LIMITE_FIN_CLASES: '21:00',
  DURACION_FRANJA_MINUTOS: 60,
  DIAS_LABORABLES: ['LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES'],
  DIAS_FIN_SEMANA: ['SABADO', 'DOMINGO'],
  HORAS_MAX_DIARIAS_DEFAULT: 8,
  HORAS_MAX_CONTINUAS_DEFAULT: 4,
  DESCANSO_MIN_ENTRE_HORAS: 1,
};

export const PAGINACION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
};

export const CACHE = {
  TTL_DISPONIBILIDAD: 300, // 5 minutos
  TTL_SELECCION_TEMPORAL: 1800, // 30 minutos
  TTL_ESTADISTICAS: 600, // 10 minutos
};

export const RATE_LIMIT = {
  WINDOW_MS: 15 * 60 * 1000, // 15 minutos
  MAX_REQUESTS: 100,
  AUTH_MAX_REQUESTS: 5, // Para endpoints de autenticación
};

export const TOKENS = {
  ACCESS_TOKEN_EXPIRY: '24h',
  REFRESH_TOKEN_EXPIRY: '7d',
  RESET_TOKEN_EXPIRY: 3600, // 1 hora en segundos
};

export const NOTIFICACIONES = {
  FRECUENCIA_MAX_DIARIA: 10,
  REINTENTOS_MAX: 3,
  DELAY_REINTENTO: 5000, // 5 segundos
};

export const ARCHIVOS = {
  TIPOS_PERMITIDOS: ['.csv', '.xlsx', '.xls'],
  TAMANO_MAX: 5 * 1024 * 1024, // 5MB
  TIPOS_IMAGEN: ['image/jpeg', 'image/png', 'image/webp'],
};

export const ROLES = {
  ADMINISTRADOR: 'ADMINISTRADOR',
  SECRETARIA: 'SECRETARIA',
  OPERADOR: 'OPERADOR',
  DOCENTE: 'DOCENTE',
  MONITOR: 'MONITOR',
} as const;

export const PERMISOS = {
  GESTIONAR_USUARIOS: [ROLES.ADMINISTRADOR],
  GESTIONAR_DOCENTES: [ROLES.ADMINISTRADOR, ROLES.SECRETARIA],
  GESTIONAR_CURSOS: [ROLES.ADMINISTRADOR, ROLES.SECRETARIA],
  GESTIONAR_HORARIOS: [ROLES.ADMINISTRADOR, ROLES.SECRETARIA, ROLES.OPERADOR],
  PUBLICAR_HORARIOS: [ROLES.ADMINISTRADOR, ROLES.SECRETARIA],
  VER_HORARIOS: [ROLES.ADMINISTRADOR, ROLES.SECRETARIA, ROLES.OPERADOR, ROLES.DOCENTE],
  GESTIONAR_VENTANAS: [ROLES.ADMINISTRADOR, ROLES.SECRETARIA, ROLES.OPERADOR],
  VER_REPORTES: [ROLES.ADMINISTRADOR, ROLES.SECRETARIA],
  CONFIGURAR_SISTEMA: [ROLES.ADMINISTRADOR],
} as const;